name: remote ssh command
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ secrets.KEY }}" > key
            - run: chmod 600 key
            # - run: cat key
            - run: ssh -v -i key ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} 'ls -l'
