name: remote ssh command
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              run: echo ${{ secrets.KEY }} > key
              run: cat key
              run: ssh -i key ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'ls -l'
