name: remote ssh command
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ secrets.KEY }}" > ~/.ssh/id_ed25519
            - run: chmod 600 ~/.ssh/id_ed25519
            - run: cat key
            - run: ssh -v -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} 'ls -l'
